# FUNDING.yml
github: [andrescastiglia]
open_collective: dorrego
patreon: acastiglia
custom: ["https://www.mercadopago.com.ar/checkout/v1/redirect?preference-id=79658682-7b958688-67d6-42cc-a09a-4915d8fe6558"]
