name: publishing

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  push_to_registry:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Metadata
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: acastiglia/dorrego

    - name: Build and Push
      id: push
      uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Attestation
      uses: actions/attest-build-provenance@v2
      with:
        subject-name: docker.io/acastiglia/dorrego
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true